/**
 * Trigger Handler for associated object type.
 *
 * @author		Arturs Gusjko
 */
public with sharing class {{ api_name }} extends AbstractTrigger
{
	/************* TRIGGER EVENTS ***************/



	/************* HELPERS *************/

	/************* GENERIC METHODS **************/

	/*
	// without sharing logic goes inside this class and is exposed via wrapping methods.
	private without sharing class {{ api_name }}WithoutSharing
	{
		
	}

	static private final {{ api_name }}WithoutSharing withoutSharing = new {{ api_name }}WithoutSharing();
	*/
}