/**
 * {{ class_description }}
 *
 * @author		Arturs Gusjko
 */
global class {{ api_name }} implements Site.UrlRewriter
{
	
	/**
	 * Incoming url from user browser.
	 */
	global PageReference mapRequestUrl(PageReference yourFriendlyUrl)
	{
		
		return null;
	}
	
	/**
	 * Urls displayed in links.
	 */
	global List<PageReference> generateUrlFor(List<PageReference> yourSalesforceUrls)
	{
		
		return null;
	}
	
}